# https://hub.docker.com/_/rabbitmq
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=shoukii
      - RABBITMQ_DEFAULT_PASS=shouadmin
    networks:
      - rabbitmq

networks:
  rabbitmq:
    driver: bridge
